version: '3.8'

services:
  ai-agent:
    build: .
    container_name: multimodal-ai-agent
    ports:
      - "8501:8501"  # Streamlit应用
      - "8080:8080"  # 健康检查端点
    environment:
      # OpenAI API配置
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      
      # Volcano Engine ARK API配置
      - ARK_API_KEY=${ARK_API_KEY}
      - ARK_BASE_URL=${ARK_BASE_URL:-https://ark.cn-beijing.volces.com/api/v3}
      - ARK_MODEL=${ARK_MODEL:-ep-20250506230532-w7rdw}
      
      # 性能优化配置
      - OPTIMIZATION_LEVEL=${OPTIMIZATION_LEVEL:-balanced}
      - ENABLE_CACHING=${ENABLE_CACHING:-true}
      - ENABLE_CONNECTION_POOLING=${ENABLE_CONNECTION_POOLING:-true}
      - ENABLE_ASYNC_PROCESSING=${ENABLE_ASYNC_PROCESSING:-true}
      - ENABLE_PERFORMANCE_MONITORING=${ENABLE_PERFORMANCE_MONITORING:-true}
      
      # 缓存配置
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE:-1000}
      - CACHE_DEFAULT_TTL=${CACHE_DEFAULT_TTL:-3600}
      - CACHE_EVICTION_POLICY=${CACHE_EVICTION_POLICY:-lru}
      - CACHE_ENABLE_PERSISTENCE=${CACHE_ENABLE_PERSISTENCE:-true}
      
      # 连接池配置
      - HTTP_POOL_SIZE=${HTTP_POOL_SIZE:-10}
      - HTTP_MAX_RETRIES=${HTTP_MAX_RETRIES:-3}
      - HTTP_TIMEOUT=${HTTP_TIMEOUT:-30}
      
      # 异步处理配置
      - ASYNC_MAX_WORKERS=${ASYNC_MAX_WORKERS:-4}
      - ASYNC_QUEUE_SIZE=${ASYNC_QUEUE_SIZE:-100}
      
      # 监控配置
      - MONITOR_INTERVAL=${MONITOR_INTERVAL:-60}
      - MONITOR_HISTORY_SIZE=${MONITOR_HISTORY_SIZE:-1000}
      
      # 安全配置
      - ENABLE_SECURITY=${ENABLE_SECURITY:-true}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-3600}
      
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./data:/app/data
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/quick"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Prometheus监控
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-agent-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    profiles:
      - monitoring
    depends_on:
      - ai-agent

  # Grafana仪表板
  grafana:
    image: grafana/grafana:latest
    container_name: ai-agent-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/ai-agent.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    profiles:
      - monitoring
    depends_on:
      - prometheus

  # GraphQL API服务
  graphql-api:
    build: .
    container_name: ai-agent-graphql
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ARK_API_KEY=${ARK_API_KEY}
      - ARK_BASE_URL=${ARK_BASE_URL:-https://ark.cn-beijing.volces.com/api/v3}
      - ARK_MODEL=${ARK_MODEL:-ep-20250506230532-w7rdw}
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
    command: ["python", "api/graphql_server.py"]
    profiles:
      - api
    depends_on:
      - ai-agent

  # 移动端API服务
  mobile-api:
    build: .
    container_name: ai-agent-mobile-api
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ARK_API_KEY=${ARK_API_KEY}
      - ARK_BASE_URL=${ARK_BASE_URL:-https://ark.cn-beijing.volces.com/api/v3}
      - ARK_MODEL=${ARK_MODEL:-ep-20250506230532-w7rdw}
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
    command: ["python", "api/mobile_api.py"]
    profiles:
      - api
    depends_on:
      - ai-agent

  # Elasticsearch (ELK Stack)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ai-agent-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    profiles:
      - elk

  # Kibana (ELK Stack)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: ai-agent-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    profiles:
      - elk
    depends_on:
      - elasticsearch

volumes:
  prometheus_data:
  grafana_data:
  elasticsearch_data:

networks:
  default:
    name: ai-agent-network
